---
title: "Trait_Setup"
author: "Ben J. Rivera"
date: "2023-04-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(here)
library(rtry)
library(googlesheets4)


```




## Try Data processing
```{r} 
TryData<- rtry_import(here("EnteredData", "TryData", "Traits.txt"))

TryCat<- subset(TryData, OrigUnitStr== "" )
TryQuant<- subset(TryData, OrigUnitStr != "" & is.na(StdValue) == FALSE )

QuantTrait<-TryQuant %>%
  select(AccSpeciesName,DataName, StdValue) %>%
  group_by(AccSpeciesName,DataName) %>%
  summarise(mean = mean(StdValue)) %>%
  pivot_wider(names_from = DataName, values_from = mean, values_fill = NA)


pastey<- purrr::partial(base::paste, sep="; ")


p <- function(v) {
  Reduce(f=pastey, x = v)
}
CatTrait<- TryCat %>% 
  select(AccSpeciesName,DataName, OrigValueStr) %>%
  group_by(AccSpeciesName,DataName) %>%
  summarise(all = p(unique(OrigValueStr))) %>%
  pivot_wider(names_from = DataName, values_from = all, values_fill = NA)


gs4_auth() #signs you in so it can upload to google sheets

#### This gives you the ability to alter sheets on your google drive ###

gs4_create("CategoricalDuneTraits", sheets = list(data = CatTrait)) #uploads list of publications and all the info to a google sheets
gs4_create("QuantitativeDuneTraits", sheets = list(data = QuantTrait)) #uploads list of publications and all the info to a google sheets

```
```

